#!/bin/bash
source ./env
source ./lib

# Remove old staging dir
rm -rf ${STAGING_DIR}
mkdir -p ${STAGING_DIR}

restore

#CONTAINERS=$(docker ps -q)
#docker stop ${CONTAINERS}
#rsync --archive --progress --delete ${STAGING_DIR}/ ${LOCAL_DIR}/
#docker start ${CONTAINERS}

source ./unset-env
